name: filesList

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: ----
        run: ls > fileList.txt
      - name: ----
        run: ls
      - name: Every time
        run: echo "This step will always run"
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
