name: filesList

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: ----
        run: ls > echo
      - name: ----
        run: ls | echo
      - name: Every time
        run: echo "This step will always run"
